#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.openvpn_client
	set firewall.openvpn_client=include
	set firewall.openvpn_client.type=script
	set firewall.openvpn_client.path=/var/etc/luci-app-openvpn-client.include
	set firewall.openvpn_client.reload=1
EOF

# OpenVPN客户端配置
cat > /etc/config/luci-app-openvpn-client << 'OPENVPN_CONFIG'
config clients
	option port '1194'
	option proto 'tcp'
	option dev 'tun'
	option lzo '1'
	option route_nopull '0'
	option allow_access '1'
	option auth 'user_pass'
	option username 'tr0001'
	option password 'kiss19776'
	option enabled '0'
	option server 'lingdunkeji.com'
	option ca '-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgIJAI5SAGm2J7LeMA0GCSqGSIb3DQEBCwUAMDcxCzAJBgNV
BAYTAkNOMQ4wDAYDVQQKDAVpS3VhaTEYMBYGA1UEAwwPaUt1YWkgRGV2aWNlIENB
MB4XDTI2MDQwNjEzMTQzNloXDTM2MDQwMzEzMTQzNlowNzELMAkGA1UEBhMCQ04x
DjAMBgNVBAoMBWlLdWFpMRgwFgYDVQQDDA9pS3VhaSBEZXZpY2UgQ0EwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDe6X1lQrdtbwx0ocROrCQstPr8PEj4
rzRjmspcJYEPRqwuBFdrWs9SzPZGqpj7kZqUbY0ben5LzH8Oq+K2ZizxlX90/MPs
UtNWod4/w41shZdzcX+UKzLbDF0EeGWAs551fjNwyzncVWELRyLSh8SHt5ptxjCj
zMmtD2F2TZ2vTruR/Fx4x/BboGYNsh1wPWasK9A1//ZyQi5l7QVnLdnxj1iq8krB
C5txu159Q6r9ITgDcL35QX4fwSeBWvFIjPvTF+a74NZ3ptcBxJW/ehGh3mvPUUIT
E5QGlahCJhDWLp8BT6ngnRoB96F+P3AQ9dKFas1XSA13P8Fkq2wF0hhpAgMBAAGj
UDBOMB0GA1UdDgQWBBRj8EU3ImPPf460R8LaZ8vx6wiYRjAfBgNVHSMEGDAWgBRj
8EU3ImPPf460R8LaZ8vx6wiYRjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQBNhFW6UUXeKsTu8pSskUY4qBsHKkqHk2JUkb1Mm8+bSLEiKAydk2sCvM5Z
IWVXsXiwAlrxUPLKoegfQZD+3zazIdt+FxGPgbGxTXylhlCnuTKLGyex8/laQ4l9
xOijSnvSTnD528jvYav+dcVb8Y1tWXswVequHcJyBnTMRG9bxRnoCKZcsWSq5fm0
ZqIBkFMzekn4dWPbI7kEn3d2m7iX4a0qzk3jbSDcVpc5C6xUfLv5a1qSVkQdiQpT
v5MbjCz8dPdyGus6VlpW8/bCBd8eNUyFjA9yxlbkHDT03zW9gXFrGQtHqmx9x5Yn
MRM1TTdnKuB4nr5919kIwFE4IaXB
-----END CERTIFICATE-----'
	option extra_config 'resolv-retry infinite
reneg-sec 0
cipher AES-256-GCM
key-direction 1
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
6e201c04fb2a05d5355cfe6fe01ca344
4649bb48405b926aa89a7deff2352284
d48d655be94eb9370f395be893e5da2f
185c587624692ae42f7eb14c00a48c24
57d5ae1b6a81721107e695b5af6cbca6
a66919fd0b7c55a3c147088905256cd4
43cafca7ee46a5cb2d4f48c568e23e64
ad775894870d61fe8918c5c006c6c292
7bcbbac1e2ff636779451fccd679cd8a
e0e9c15997b6f5b2b7c4272ea5c2fdc9
d91ef2c89bda83916b8e437413084436
a5acf8d38abeaa00d6d1d6123b3b1110
7cab3e3a274e405ca8cf06ce15aa3baf
c7249e247ca56ff7cbad716a0d4f366d
36b29afac62be9f3bf7fe2797b9723fe
4103ada3267bb19da9fdd3eea802f154
-----END OpenVPN Static key V1-----
</tls-auth>'
OPENVPN_CONFIG

# /etc/config/network
if ! uci -q get network.vpn >/dev/null 2>&1; then
	uci set network.vpn=interface
	uci set network.vpn.proto='none'
	uci set network.vpn.device='ovpn_cfg019277'
	uci set network.vpn.delegate='0'
	uci commit network
	# /etc/config/firewall
	uci add firewall zone 
	uci set firewall.@zone[-1].name='vpn'
	uci set firewall.@zone[-1].input='ACCEPT'
	uci set firewall.@zone[-1].output='ACCEPT'
	uci set firewall.@zone[-1].forward='ACCEPT'
	uci add_list firewall.@zone[-1].network='vpn'
	uci add firewall forwarding 
	uci set firewall.@forwarding[-1].src='vpn'
	uci set firewall.@forwarding[-1].dest='lan'
	uci add firewall forwarding 
	uci set firewall.@forwarding[-1].src='vpn'
	uci set firewall.@forwarding[-1].dest='wan'
	uci add firewall forwarding
	uci set firewall.@forwarding[-1].src='lan'
	uci set firewall.@forwarding[-1].dest='vpn'
	uci commit firewall
	/etc/init.d/network restart
	/etc/init.d/firewall restart
fi

rm -rf /tmp/luci-*cache
exit 0
